./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_00.mp4 #./results/test_00.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_01.mp4 #./results/test_01.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_02.mp4 #./results/test_02.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_03.mp4 #./results/test_03.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_04.mp4 #./results/test_04.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_05.mp4 #./results/test_05.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_06.mp4 #./results/test_06.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_07.mp4 #./results/test_07.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_08.mp4 #./results/test_08.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_09.mp4 #./results/test_09.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_10.mp4 #./results/test_10.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_11.mp4 #./results/test_11.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_12.mp4 #./results/test_12.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_13.mp4 #./results/test_13.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_14.mp4 #./results/test_14.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_15.mp4 #./results/test_15.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_16.mp4 #./results/test_16.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_17.mp4 #./results/test_17.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_18.mp4 #./results/test_18.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_19.mp4 #./results/test_19.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_20.mp4 #./results/test_20.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_21.mp4 #./results/test_21.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_22.mp4 #./results/test_22.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_23.mp4 #./results/test_23.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_24.mp4 #./results/test_24.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_25.mp4 #./results/test_25.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_26.mp4 #./results/test_26.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_27.mp4 #./results/test_27.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_28.mp4 #./results/test_28.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_29.mp4 #./results/test_29.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_30.mp4 #./results/test_30.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_31.mp4 #./results/test_31.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_32.mp4 #./results/test_32.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_33.mp4 #./results/test_33.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_34.mp4 #./results/test_34.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_35.mp4 #./results/test_35.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_36.mp4 #./results/test_36.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_37.mp4 #./results/test_37.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_38.mp4 #./results/test_38.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_39.mp4 #./results/test_39.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_40.mp4 #./results/test_40.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_41.mp4 #./results/test_41.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_42.mp4 #./results/test_42.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_43.mp4 #./results/test_43.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_44.mp4 #./results/test_44.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_45.mp4 #./results/test_45.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_46.mp4 #./results/test_46.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_47.mp4 #./results/test_47.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_48.mp4 #./results/test_48.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_49.mp4 #./results/test_49.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_50.mp4 #./results/test_50.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_51.mp4 #./results/test_51.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_52.mp4 #./results/test_52.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_53.mp4 #./results/test_53.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_54.mp4 #./results/test_54.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_55.mp4 #./results/test_55.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_56.mp4 #./results/test_56.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_57.mp4 #./results/test_57.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_58.mp4 #./results/test_58.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_59.mp4 #./results/test_59.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_60.mp4 #./results/test_60.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_61.mp4 #./results/test_61.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_62.mp4 #./results/test_62.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_63.mp4 #./results/test_63.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_64.mp4 #./results/test_64.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_65.mp4 #./results/test_65.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_66.mp4 #./results/test_66.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_67.mp4 #./results/test_67.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_68.mp4 #./results/test_68.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_69.mp4 #./results/test_69.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_70.mp4 #./results/test_70.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_71.mp4 #./results/test_71.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_72.mp4 #./results/test_72.txt
./a.out ~/Desktop/ultra96_vai1_4/ai-edge-contest-5/dataset/test_videos/test_73.mp4 #./results/test_73.txt
